### ISSUE TITLE
Working state

### ISSUE THREAD

**Issue by davidgraeff** [maggu2810/openhab-demo#1]
Can you try to build this one yourself when you have time? 

I kind of made this repository a first-entrance point by adding it to the openhab2-addons readme. But it does not work recently and people reported to not have rest api access with the provided bndrun file.

Cheers, David

**Comment by maggu2810** [comment]
I will give it a try.
The first issue I found will be fixed by https://github.com/openhab/openhab2-addons/pull/5342

Will check for others.

**Comment by cweitkamp** [comment]
https://github.com/openhab/openhab2-addons/pull/5342 has been merged.

**Comment by maggu2810** [comment]
I rerun the resolver to update to the current ohc master dependencies (Xtext 2.17 etc.).

For me it is working using Java 8 (tested Paper UI and so some REST API calls).

**Comment by maggu2810** [comment]
@davidgraeff Anything still missing?

**Comment by davidgraeff** [comment]
It doesn't work for people in the forum. See https://community.openhab.org/t/need-some-help-with-setup-to-create-new-binding-using-maven-bnd/70901/19

**Comment by davidgraeff** [comment]
I have created a travis CI file so that we can keep an eye on the build state.

Can you connect the travis github app with this repo and setup a travis cron job for like every 7 days or so?
