### ISSUE TITLE
org.eclipse.smarthome.core.internal.events.OSGiEventPublisher

### ISSUE THREAD

**Issue by davidgraeff** [maggu2810/openhab-demo#3]
When running this demo app, I do encounter some unexpected behaviour like that the `org.eclipse.smarthome.core.internal.events.EventPublisher` component is not satisfied.

```
Unsatisfied
Service Name: org.eclipse.smarthome.core.events.EventPublisher
Cardinality: 1..1
Policy: static
Policy Option: reluctant
No Services bound
```

| Bundle | org.openhab.core (53) |
| -- | -- |
Implementationsklasse | org.eclipse.smarthome.core.internal.events.OSGiEventPublisher
Default Status | enabled
Aktivierung | delayed
Konfigurations Policy | optional
Dienst Typ | singleton
Dienste | org.eclipse.smarthome.core.events.EventPublisher
PID | org.eclipse.smarthome.core.internal.events.OSGiEventPublisher
Reference EventAdmin | Unsatisfied, Service Name: org.osgi.service.event.EventAdmin, Cardinality: 1..1, Policy: static, Policy Option: reluctant, No Services bound
Eigenschaften | component.id = 7, component.name = org.eclipse.smarthome.core.internal.events.OSGiEventPublisher

It almost looks like a `org.apache.felix.eventadmin` or similar is missing, but I'm not familiar with OSGi implementations. Is everything starting up for you?

**Comment by maggu2810** [comment]
I would expect that [org.eclipse.equinox.event](https://github.com/maggu2810/openhab-demo/blob/d0898fa/app/app.bndrun#L109) provides that service.

**Comment by davidgraeff** [comment]
That line is missing in my app.bndrun file. Because I haven't removed it myself, that must have been the resolved I guess. Thanks.

**Comment by maggu2810** [comment]
You need to remember that resolve is broken as long as the DS requirements are not added to the manifest.
